server:
  port: 8181
  address: 0.0.0.0
  host: http://localhost
  base-url: ${server.host}:${server.port}/

frontend:
  port: 4200
  domain: ${server.host}:${frontend.port}
  forgot_password: /auth/reset-password
  verify_email: /auth/verify-email


spring:
  application:
    name: bdfs

  datasource:
    url: jdbc:postgresql://localhost:5432/bdfs
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

jwt:
  rsa-private-key: classpath:certs/private_key.pem
  rsa-public-key: classpath:certs/public_key.pem

app:
  filepath:
    windows: D:\\bdfs\\
    linux: /home/user/bdfs/
    mac: /Users/bdfs/

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    path: /v1/swagger

otp:
  expiryInSeconds: 300 # OTP expiry time in seconds (5 minutes)


# Mail Configuration
google:
  email: ps9594083@gmail.com
  password: qbma vtiw gwwc wghx
